# Generated by Django 2.0.1 on 2018-02-05 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0002_auto_20180205_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_received', to=settings.AUTH_USER_MODEL)),
                ('inviting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_sent', to=settings.AUTH_USER_MODEL)),
                ('target_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_platform.Question')),
            ],
        ),
    ]
