# Generated by Django 2.0.1 on 2018-02-05 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0004_auto_20180205_2240'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitationtoanswer',
            unique_together={('inviting_user', 'invited_user', 'target_question')},
        ),
    ]
