# Generated by Django 2.0.1 on 2018-02-08 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0007_match_matchrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='mentee',
        ),
        migrations.RemoveField(
            model_name='match',
            name='mentor',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
