# Generated by Django 2.0.1 on 2018-02-08 15:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0008_auto_20180208_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mentors',
            field=models.ManyToManyField(blank=True, related_name='mentees', to=settings.AUTH_USER_MODEL),
        ),
    ]
