# Generated by Django 2.0.1 on 2018-02-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0009_user_mentors'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrequest',
            name='is_declined',
            field=models.BooleanField(default=False),
        ),
    ]
