# Generated by Django 2.0.1 on 2018-02-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0010_matchrequest_is_declined'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrequest',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='matchrequest',
            unique_together={('mentee', 'mentor')},
        ),
    ]
